### ISSUE TITLE
CallBacks for event and functions for startListening,stopListening,abort etc..?

### ISSUE THREAD

**Issue by hvardhan617** [FoundersFactory/react-speech-recognition#12]
Will we get any callbacks while invoking async functions such as startListening,stopListening,abortListening ?
If so, how can we handle the callbacks?

**Comment by JamesBrill** [comment]
There are two ways you can do this:

- Use the [built-in event handlers](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/onend) in the Speech Recognition object, which is given to you as a property called `recognition`. You can set these to your callback function when constructing or mounting your component:
```
    const { recognition } = this.props
    recognition.onend = () => console.log("Listening has stopped");
    recognition.onstart = () => console.log("Listening has started");
```
- Detect changes to the `listening` property, which is another property injected by `react-speech-recognition`. If you're using a class-based React component, you can pick up these changes in the `componentWillReceiveProps` lifecycle hook. For example:
```
  componentWillReceiveProps(nextProps) {
    if (this.props.listening !== nextProps.listening) {
      console.log(nextProps.listening);
    }
  }
```

Hope that helps!
