### ISSUE TITLE
Recognition has stopped working

### ISSUE THREAD

**Issue by Mykasoda** [FoundersFactory/react-speech-recognition#13]
Hi, I've been using this for about 8 months now and it's worked great, but all of a sudden it won't work for me.

In my main app as well as just creating a simple app with just the getting started code.

It's not throwing an error or anything, the app compiles fine but then just does nothing in the browser.

Please advise. I know this is kind of ambiguous but I'm not sure what other info I can provide. Would appreciate any info greatly :)

**Comment by JamesBrill** [comment]
- Which version are you using?
- Which options are you setting on `SpeechRecognition`?
- If you debug or `console.log` the properties injected by `SpeechRecognition`, what do you see?

**Comment by Mykasoda** [comment]
Version: 1.1.0
Options: none, just the default.
Console.log for these items...
        console.log(transcript);
        console.log(resetTranscript);
        console.log(browserSupportsSpeechRecognition);

returns "True", a blank line, and a function...

"ƒ () {
          interimTranscript = '';
          finalTranscript = '';
          _this.disconnect('RESET');
          _this.setState({ interimTranscript: interimTranscript, finalTranscript: finalTran…"

Haha, no, not offline, you made that clear it's not possible :) Even in that case though it gave an error, this is just nothing.

Here is the full code of the app I'm trying to make work now. It was just taken from a stack exchange sample file.
`import React, {Component } from 'react'
import SpeechRecognition from 'react-speech-recognition'

class Dictaphone extends Component {
  render() {
    const { transcript, resetTranscript, browserSupportsSpeechRecognition } = this.props

    if (!browserSupportsSpeechRecognition) {
      return null
    }

    return (
      <div>
        <button onClick={resetTranscript}>Reset</button>
        <span>{transcript}</span>
      </div>
    )
  }
}

export default SpeechRecognition(Dictaphone)`

**Comment by JamesBrill** [comment]
I have used this same example code using version 1.1.0 and it behaves as normal.

When you run the app, do you see the red recording icon in your Chrome tab?
<img width="183" alt="Screen Shot 2019-03-28 at 22 06 58" src="https://user-images.githubusercontent.com/2140027/55196006-04e44300-51a6-11e9-9a93-6cd1bfb170be.png">

**Comment by Mykasoda** [comment]
No. I used to, but now for some reason it doesn't. I must've done something to goof it up, but not sure how to track it down since it was working last time I ran it about 3 weeks ago.

**Comment by JamesBrill** [comment]
To help me determine if this is a bug in 1.1.0 (which was released last week), can you revert back to 1.0.7 and see if you still get the issue?

**Comment by JamesBrill** [comment]
Hard-code the version with:
```
"react-speech-recognition": "1.0.7",
```

in your `package.json` and then run `npm install`.

**Comment by JamesBrill** [comment]
Another test to see if the Web Speech API is working in your browser:
- Open Dev Tools
- Open Console
- Run
```
const recognition = new webkitSpeechRecognition();
recognition.start();
```
- Do you see the red recording icon?

**Comment by JamesBrill** [comment]
Another possibility is that you accidentally blocked your app from using your microphone in Chrome. If that is the case, you will see this icon in the right-hand side of your address bar:
<img width="45" alt="Screen Shot 2019-03-28 at 22 16 21" src="https://user-images.githubusercontent.com/2140027/55196403-2c87db00-51a7-11e9-8890-daeee7816969.png">

**Comment by Mykasoda** [comment]
Using 1.0.7 did not fix.
It's not the blocked microphone, checked that earlier.

When I try to run...

**Comment by JamesBrill** [comment]
> When I try to run...
> 
> const recognition = new webkitSpeechRecognition();
> recognition.start();
> 
> I get...
> 
> undefined

Yes, but does the recognition start and the red icon appear on your tab?

**Comment by Mykasoda** [comment]
No

**Comment by JamesBrill** [comment]
Which browser are you using?

**Comment by Mykasoda** [comment]
Google Chrome
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by JamesBrill** [comment]
I have the same version and the two lines of code I posted above turned on the recognition. Web Speech API isn't working in your browser for some reason.

Two thoughts:
- Restart your browser and run those two lines again
- Is your microphone broken?

**Comment by Mykasoda** [comment]
gonna restart whole computer again, and browser, and then test mic, will be back with results.

**Comment by JamesBrill** [comment]
Haha drastic measures indeed! :D I look forward to the results.

**Comment by Mykasoda** [comment]
still not working :(

I restarted computer, restarted chrome and disabled all extensions... I gotta be doing something really stupid to make this not work lol

**Comment by Mykasoda** [comment]
oh and mic seems to be working, did a test record and the test setup in system prefs

**Comment by JamesBrill** [comment]
And to reiterate, when you run
```
const recognition = new webkitSpeechRecognition();
recognition.start();
```
in a new tab, you do not see the flashing red recording icon in your tab?

**Comment by Mykasoda** [comment]
correct.

**Comment by JamesBrill** [comment]
What properties are on your `recognition` object? Just run `recognition`. Do you see an object like this?
<img width="753" alt="Screen Shot 2019-03-28 at 22 40 21" src="https://user-images.githubusercontent.com/2140027/55197416-70c8aa80-51aa-11e9-8670-458302e3bfef.png">

**Comment by Mykasoda** [comment]
![Screen Shot 2019-03-28 at 3 41 17 PM](https://user-images.githubusercontent.com/7808729/55197521-1874b700-5170-11e9-9167-0bc101146205.png)

**Comment by JamesBrill** [comment]
Did you instantiate it first?

**Comment by JamesBrill** [comment]
```
const recognition = new webkitSpeechRecognition();
recognition
```

**Comment by Mykasoda** [comment]
![Screen Shot 2019-03-28 at 3 41 17 PM](https://user-images.githubusercontent.com/7808729/55197570-3e9a5700-5170-11e9-8807-d2b9c6640218.png)

**Comment by Mykasoda** [comment]
![Screen Shot 2019-03-28 at 3 43 27 PM](https://user-images.githubusercontent.com/7808729/55197593-4a861900-5170-11e9-8396-dbe6b357e752.png)

**Comment by JamesBrill** [comment]
And when you run `recognition.start()`, no flashing icon...

Here's a good test: try this website https://www.cs.cmu.edu/~dst/SpeechDemo/

**Comment by Mykasoda** [comment]
yeah, super weird.

![Screen Shot 2019-03-28 at 3 45 46 PM](https://user-images.githubusercontent.com/7808729/55197731-a2248480-5170-11e9-8927-10c2989a30d4.png)

This is interesting, it's saying not allowed even though in site settings it's set to "ask" and when I toggle it to "allowed" it still says not allowed. I wonder if there's some global permission I messed up at some point.

**Comment by JamesBrill** [comment]
Could you screenshot the thing that says the microphone is not allowed?

**Comment by Mykasoda** [comment]
![Screen Shot 2019-03-28 at 3 49 34 PM](https://user-images.githubusercontent.com/7808729/55197858-1a8b4580-5171-11e9-8bd9-6a397d5f945b.png)

**Comment by JamesBrill** [comment]
I'm pulling at straws here, but is it possible that Chrome itself is blocked by your operating system from using the microphone? You mentioned System Preferences earlier, so I guess you're using a Mac. Maybe check this out? https://support.apple.com/en-gb/guide/mac-help/control-access-to-your-microphone-on-mac-mchla1b1e1fe/mac

**Comment by JamesBrill** [comment]
Though that link says you'd get prompted if the app tried to access the microphone again...

**Comment by Mykasoda** [comment]
THAT WAS IT!!!!!

THANKS FOR GRASPING THE STRAWS!!!

I was googling for hours for something like this but just kept coming across stuff about SSLs.

I guess this was in the system update and I just had no idea it was even a thing.

AGAIN THANK YOU SO MUCH (and sorry it had nothing to do with your component really).

**Comment by Mykasoda** [comment]
> Though that link says you'd get prompted if the app tried to access the microphone again...

Yeah, it says that, but there was no such prompt lol hence having no idea where to check. Thank you again!

**Comment by JamesBrill** [comment]
Glad to hear you're unblocked! This was fun. 😄
