### ISSUE TITLE
Does not fail gracefully on Safari

### ISSUE THREAD

**Issue by ish-joshi** [FoundersFactory/react-speech-recognition#16]
![image](https://user-images.githubusercontent.com/25214445/55530645-a0b80680-56f2-11e9-955b-bca4ec82c6c1.png)

The graceful exit does not work on safari as it's trying to do computation with 'recognition' variable when it's null. Safari is not a supported browser. 

Hence, a possible fix is adding the if statement (commented out below)

![image](https://user-images.githubusercontent.com/25214445/55530689-cb09c400-56f2-11e9-987e-784f6be9197c.png)

I've also added a pull request https://github.com/FoundersFactory/react-speech-recognition/pull/17

**Comment by JamesBrill** [comment]
Thanks for raising this! I've merged your PR and will publish a new version immediately.

**Comment by JamesBrill** [comment]
Fixed in version 2.0.1

Thanks for your contribution!
