### ISSUE TITLE
Start/Stop sound in mobile chrome

### ISSUE THREAD

**Issue by Desintegrator** [FoundersFactory/react-speech-recognition#25]
How to disable sound effects when recognition starts or stop?

**Comment by farhanbombay** [comment]
Android limitations, I am also frustrated

**Comment by JamesBrill** [comment]
Hi @Desintegrator can you elaborate on what you mean by "sound effects"? Does the browser actually play a sound when speech recognition is turned on or off?

I have not experienced this before, but I imagine that these sound effects would be controlled either by the browser or the OS. There is no mention of controlling such sound effects in the Speech Recognition [docs](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition).

**Comment by JamesBrill** [comment]
Ah yes, I just reproduced this on Android. The sound effects are indeed annoying. However, they seem to be controlled by the OS, so I don't think this is something we can control sadly.
