### ISSUE TITLE
Transcript multiple language

### ISSUE THREAD

**Issue by webbieram** [FoundersFactory/react-speech-recognition#27]
Hi,

first of all great to this react plugin. I would like to have an option to choose language from dropdown and according to that the transcription should work. Is there any way to do that?

Thanks in advance

**Comment by JamesBrill** [comment]
Hi @webbieram React Speech Recognition will inject a prop into your component called `recognition` (see [this](https://github.com/FoundersFactory/react-speech-recognition#recognition-object)). You can set the language used by Speech Recognition by assigning a language value to the `lang` property on this object. This value must be a valid [BCP 47 language tag](https://en.wikipedia.org/wiki/IETF_language_tag) (as required [here]( https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/lang)).

You could do the following:
- Have a dropdown with labels for different languages
- Each label would have a language tag value behind it. For example, `Chinese` would have language tag `zh-CN`
- Whenever the selected value of this dropdown changes, assign the selected language tag to `recognition.lang`
