### ISSUE TITLE
Does this work on browsers only?

### ISSUE THREAD

**Issue by fares26597** [FoundersFactory/react-speech-recognition#29]
Hi,
I see that it works on chrome quite well. I was wondering whether it can be implemented in an android app instead of using it through a browser. Because I couldn't find a better speech library than this one, but I can't get it to work within my app.

**Comment by JamesBrill** [comment]
This is a web library intended to work in a web browser - it will not work in a native app. However, you could in theory use this inside an Android webview - it appears in the Browser Compatibility table [here](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition).
