### ISSUE TITLE
  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by samankhademi** [FoundersFactory/react-speech-recognition#5]
I think that is because there is no "window" in server side rendering
i use react Starter Kit 
  - SpeechRecognition.js:60 SpeechRecognitionInner
    [adviser-web]/[react-speech-recognition]/lib/SpeechRecognition.js:60:36
  
  - SpeechRecognition.js:213 SpeechRecognition
    [adviser-web]/[react-speech-recognition]/lib/SpeechRecognition.js:213:12
  
  - ChatMessageList.js:616 Object../src/components/ChatMessageList/ChatMessageLi    st.js
    G:/xampp/htdocs/adviser-web/src/components/ChatMessageList/ChatMessageList.j    s:616:1
  
  - bootstrap 37ce11a8a8fe752fa6d7:643 __webpack_require__
    G:/xampp/htdocs/adviser-web/webpack/bootstrap 37ce11a8a8fe752fa6d7:643:1
  
  - bootstrap 37ce11a8a8fe752fa6d7:47 fn
    G:/xampp/htdocs/adviser-web/webpack/bootstrap 37ce11a8a8fe752fa6d7:47:1
  
  - chat.js:2615 Object../src/routes/chat/Chat.js
    G:/xampp/htdocs/adviser-web/build/chunks/chat.js:2615:87
  
  - bootstrap 37ce11a8a8fe752fa6d7:643 __webpack_require__
    G:/xampp/htdocs/adviser-web/webpack/bootstrap 37ce11a8a8fe752fa6d7:643:1
  
  - bootstrap 37ce11a8a8fe752fa6d7:47 fn
    G:/xampp/htdocs/adviser-web/webpack/bootstrap 37ce11a8a8fe752fa6d7:47:1
  
  - chat.js:3131 Object../src/routes/chat/index.js
    G:/xampp/htdocs/adviser-web/build/chunks/chat.js:3131:64
  
  - bootstrap 37ce11a8a8fe752fa6d7:643 __webpack_require__
    G:/xampp/htdocs/adviser-web/webpack/bootstrap 37ce11a8a8fe752fa6d7:643:1

**Comment by JamesBrill** [comment]
This should now be fixed by #6 (version 1.0.6). On the server, it will fail gracefully; on the client, it should use the browser's `SpeechRecognition` object if it's available.
