### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by Mykasoda** [FoundersFactory/react-speech-recognition#7]
Hi,
I don't see any mention of this requiring a network connection, however when I attempt to use it offline it does not respond. (No error thrown, it just never updates the Transcript).

Is it possible to use it offline?

Any help would be very much appreciated as I'm somewhere I cannot access the internet but still would like to use the app I'm making.

**Comment by JamesBrill** [comment]
According to the [Web Speech API docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API): `On Chrome, using Speech Recognition on a web page involves a server-based recognition engine. Your audio is sent to a web service for recognition processing, so it won't work offline.`

So unfortunately, speech recognition will not function in Chrome when offline - it's probably too intensive to run in a browser directly.

There is a workaround for detecting online state: you can check the value of `navigator.onLine`. If it is `true`, you render the transcript. If it is `false`, you render whatever offline fallback you want when speech recognition is disabled. The online/offline API is pretty simple to use - you can read how to use it [here](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events).

**Comment by Mykasoda** [comment]
Oh, thank you for the response and the great module!

Sad I can't make it work offline, but it will be my goto when I get back to stable internet.
