### ISSUE TITLE
How to change language using recognition.lang?

### ISSUE THREAD

**Issue by aizuddineismail** [FoundersFactory/react-speech-recognition#8]
Hello ! 
I am a newbie programmer and I don't understand how to change the recognition.lang as stated in the documentation. Can you please clarify even more? Thank you

**Comment by aizuddineismail** [comment]
This is really helpful! I completely understood now. Thanks you very much! You've done such an amazing work!

**Comment by JamesBrill** [comment]
Thank you. 👍

**Comment by Nitzahon** [comment]
how would you implement this if Dictaphone in an functional component that uses callbacks.  For instance, maybe I want a voice command to change the language

**Comment by JamesBrill** [comment]
@Nitzahon With the current API, I would just call `startListening` again with the new language when it is selected (either via voice command or button click). This restarts the microphone with the new language being detected.

Just for fun, I took your idea and made a dummy component that can switch languages by voice command.
```
import React, { useState, useEffect } from 'react'
import SpeechRecognition, { useSpeechRecognition } from '../SpeechRecognition'

const LANGUAGE_MAP = {
  'אנגלית': 'en-GB',
  'hebrew': 'he'
}
const Dictaphone = () => {
  const [language, setLanguage] = useState('en-GB')
  const commands = Object.keys(LANGUAGE_MAP).map(language => ({
    command: language,
    callback: () => {
      setLanguage(LANGUAGE_MAP[language])
      SpeechRecognition.startListening({
        continuous: true,
        language: LANGUAGE_MAP[language]
      })
    },
    matchInterim: true
  }))
  const { transcript } = useSpeechRecognition({ commands })

  useEffect(() => {
    SpeechRecognition.startListening({
      continuous: true,
      language: 'en-GB'
    })
  }, [])
  
  if (!SpeechRecognition.browserSupportsSpeechRecognition()) {
    return null
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      <span>language: {language}</span>
      <span>{transcript}</span>
    </div>
  )
}

export default Dictaphone
```

Using voice command to change language is not a good idea as you will need to map the name of every language to its translation in every other language. Worse still, the browser will only understand speech in the currently selected language. For example, when the browser is listening for Hebrew, it will not be able to detect the word "english", so you would have to detect אנגלית and map that to `en-GB`. It's possible that the user may not be able to speak the currently selected language. For example, imagine a French user arrives at this app and English is detected by default - they may not know the English word for "French". It would probably be easier to let users change their language via a dropdown menu. Fun idea though.

**Comment by Nitzahon** [comment]
You make a good case for not making it work via voice command.  I'd probably go for a radio selection over a dropdown, since I only plan to have 2 supported languages

**Comment by lalit-ALDS** [comment]
how to add functionality, so that language detects automatic
